// Data collected via DCR - Windows - Basic - Performance Counters
// Reports System Uptime

Perf
| where CounterName == "System Up Time"
| summarize arg_max(TimeGenerated, *) by Computer
| extend
    UptimeHours = toint(CounterValue / 3600),
    RemainingMinutes = toint((CounterValue % 3600) / 60),
    RemainingSeconds = toint(CounterValue % 60)
| extend Uptime = strcat(UptimeHours, "h ", RemainingMinutes, "m ", RemainingSeconds, "s")
| project Computer, Uptime, LastCheckin = TimeGenerated
