// Data collected via DCR - Windows - Basic - Performance Counters
// Reports System Uptime

Perf
| where CounterName == "System Up Time"
| summarize MaxSystemUpTime = max(CounterValue) by Computer
| extend UptimeHours = toint(MaxSystemUpTime / 3600), RemainingMinutes = toint((MaxSystemUpTime % 3600) / 60), RemainingSeconds = toint(MaxSystemUpTime % 60)
| extend Uptime = strcat(UptimeHours, "h ", RemainingMinutes, "m ", RemainingSeconds, "s")
| project Computer, Uptime
